#!/data/data/com.termux/files/usr/bin/sh
# SPDX-FileCopyrightText: (C) 2026 Deskflow Developers
# SPDX-License-Identifier: MIT

set -u

config_path=${DESKFLOW_TERMUX_ENV:-"$HOME/.config/deskflow-termux-dex/service.env"}
retry_seconds=${DESKFLOW_SERVICE_RETRY_SECONDS:-10}
core_pid=

log_message()
{
  printf '%s %s\n' "$(date '+%Y-%m-%d %H:%M:%S')" "$*"
}

stop_core()
{
  if [ -n "$core_pid" ] && kill -0 "$core_pid" 2>/dev/null; then
    kill "$core_pid" 2>/dev/null || true
    wait "$core_pid" 2>/dev/null || true
  fi
  core_pid=
}

cleanup()
{
  stop_core
  termux-wake-unlock >/dev/null 2>&1 || true
  exit 0
}

trap cleanup HUP INT TERM

if [ ! -r "$config_path" ]; then
  log_message "configuration is missing: $config_path"
  exit 1
fi

# This file is generated by install-termux-dex-service.sh and is user-owned.
# shellcheck disable=SC1090
. "$config_path"

: "${DESKFLOW_BINARY:?DESKFLOW_BINARY is required in $config_path}"
: "${DESKFLOW_SETTINGS:?DESKFLOW_SETTINGS is required in $config_path}"

adb_binary=${DESKFLOW_ADB:-adb}
configured_serial=${DESKFLOW_ADB_SERIAL:-}

if [ ! -x "$DESKFLOW_BINARY" ]; then
  log_message "Deskflow binary is not executable: $DESKFLOW_BINARY"
  exit 1
fi
if [ ! -r "$DESKFLOW_SETTINGS" ]; then
  log_message "Deskflow settings are not readable: $DESKFLOW_SETTINGS"
  exit 1
fi

find_connected_serial()
{
  requested_serial=$1
  if [ -n "$requested_serial" ]; then
    "$adb_binary" connect "$requested_serial" >/dev/null 2>&1 || true
    if [ "$("$adb_binary" -s "$requested_serial" get-state 2>/dev/null || true)" = device ]; then
      printf '%s\n' "$requested_serial"
      return 0
    fi
  fi

  # If the configured wireless-debugging port changed, accept a sole device
  # connected manually with `adb connect NEW_ADDRESS`.
  connected_devices=$("$adb_binary" devices 2>/dev/null | awk 'NR > 1 && $2 == "device" { print $1 }')
  connected_count=$(printf '%s\n' "$connected_devices" | awk 'NF { count++ } END { print count + 0 }')
  if [ "$connected_count" -eq 1 ]; then
    printf '%s\n' "$connected_devices"
    return 0
  fi

  # Some android-tools builds support ADB TLS discovery. Termux builds that do
  # not support it simply return no endpoint and continue waiting.
  discovered_endpoint=$(
    "$adb_binary" mdns services 2>/dev/null |
      awk '$2 == "_adb-tls-connect._tcp" && $3 ~ /:[0-9]+$/ { print $3; exit }'
  )
  if [ -n "$discovered_endpoint" ]; then
    "$adb_binary" connect "$discovered_endpoint" >/dev/null 2>&1 || true
    if [ "$("$adb_binary" -s "$discovered_endpoint" get-state 2>/dev/null || true)" = device ]; then
      printf '%s\n' "$discovered_endpoint"
      return 0
    fi
  fi
  return 1
}

termux-wake-lock >/dev/null 2>&1 || log_message "warning: could not acquire Termux wake lock"
last_wait_message=

while :; do
  active_serial=$(find_connected_serial "$configured_serial" || true)
  if [ -z "$active_serial" ]; then
    if [ "$last_wait_message" != adb ]; then
      log_message "waiting for an authorized ADB device; enable Wireless debugging and run adb connect if its port changed"
      last_wait_message=adb
    fi
    sleep "$retry_seconds"
    continue
  fi

  last_wait_message=
  export QT_QPA_PLATFORM=${QT_QPA_PLATFORM:-minimal}
  export DESKFLOW_INPUT_BACKEND=${DESKFLOW_INPUT_BACKEND:-adb}
  export DESKFLOW_ADB_SERIAL=$active_serial
  export DESKFLOW_ANDROID_DISPLAY_ID=${DESKFLOW_ANDROID_DISPLAY_ID:-0}
  export DESKFLOW_ANDROID_MOUSE_MODE=${DESKFLOW_ANDROID_MOUSE_MODE:-uhid}
  export DESKFLOW_ANDROID_KEYBOARD_MODE=${DESKFLOW_ANDROID_KEYBOARD_MODE:-uhid}

  log_message "starting Deskflow client with ADB device $active_serial"
  "$DESKFLOW_BINARY" client --new-instance --settings "$DESKFLOW_SETTINGS" &
  core_pid=$!

  while kill -0 "$core_pid" 2>/dev/null; do
    sleep "$retry_seconds" &
    sleep_pid=$!
    wait "$sleep_pid" 2>/dev/null || true
    if [ "$("$adb_binary" -s "$active_serial" get-state 2>/dev/null || true)" != device ]; then
      log_message "ADB device disconnected; restarting after discovery"
      stop_core
      break
    fi
  done

  if [ -n "$core_pid" ]; then
    wait "$core_pid" 2>/dev/null || true
    core_pid=
    log_message "Deskflow client exited; retrying"
  fi
  sleep "$retry_seconds"
done
